if: tag IS blank
language: android
addons:
  apt:
    packages:
    - jq
env:
  global:
  - EMULATOR_API=android-22
  - secure: PHbO3t8cHo9sAytNXeZSsViRexX/KjH807aHsrY3QftaN894LbXoegDt82y37Rv3DT1Y9TB0hEOyI2OiJXzx3FN97iZnOhfff+CYfXJiG7Gs+IwVAC5qp/R4oiJrUaEs4QsmRAzgWSl7+NMK8uTGUfMuFt26RGE9xxltHwCZMEsXlXeeFMxxWsT4PkLAQor9m4r9DCkaglrSfs5rEbkvHr84okdUybLMlHgTLA9kfWNoxUczegVxxG70NMzne0ipdrk5BbOT6R60tQYhV90RaXy8Vbe7Hx0JpaZFSJ1LPXsaVPbV/90jOHDWLKEoS9vy2TNsABIKhn7Z3inJvy9YXPpCAd/+5tDwEOaF99ZuSmpJr3+Vlo4LLopTFcS6xUzDKrRtl5s9sNFW3J1Tq2q5ECg150ei65PY0HW7wNb7P0IcYGi8ynJbqQIp5Jv8sRt5nc6vNuIJi+l6i9rrhTZcXmbusD3C4P/UYnbxfmL0Dx7euRXledeGiS1r05NEazhVNiOczAg91krhjy/lC5N4fUgRQUOaTcwEwrJQH6P3H3TxXL41Lhm6UCI60FCm04lsjKs+rKTFYBHuXgoms+0GyfWPjSbF6ky1d+anrC0meYDx5IWxQv5AADfOldBtiUb77GaFDixn397L/snyWWZ9YYzUIZquZJ7Y2GpOzTMNBnM=
android:
  components:
  - build-tools-27.0.3
  - $EMULATOR_API
  - android-27
  - sys-img-armeabi-v7a-$EMULATOR_API
  - extra-android-support
  - extra-android-m2repository
before_script:
- echo no | android create avd --force -n test -t $EMULATOR_API --abi armeabi-v7a
- emulator -avd test -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
after_failure:
- find /home/travis/build/mftrips/buttplug-android/ -name lint-results.html -exec tail -vn +1 {} \;
before_deploy:
- find /home/travis/build/mftrips/buttplug-android/ -name lint-results.html -exec tail -vn +1 {} \;
- TAG_NAME=$(./gradlew -q printVersionName)-SNAPSHOT
- |-
  if git ls-remote --exit-code origin refs/tags/$TAG_NAME ; then
    TAG_ID=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/mftrips/buttplug-android/releases/tags/$TAG_NAME | jq -r .id)
    curl -s -H "Authorization: token $GITHUB_TOKEN" -X DELETE https://api.github.com/repos/mftrips/buttplug-android/releases/$TAG_ID
    git push --delete https://mftrips:$GITHUB_TOKEN@github.com/mftrips/buttplug-android $TAG_NAME
  fi
deploy:
  provider: releases
  api_key:
    secure: Kvqcbw0yjOy+34e+s0bCJwKqW6RR0J/hRp7DecMiNXals//w9p/lGYMQzlgbYp97p8ssqwdAx7VVIDdXYVzAUKPcH72fgBQMD1DFspjzOg37PnZBVQlteRPOH1NzR/tNYEY624dcEIJrg1Dutckq6VY9gXu/1SWPUNGSOabqkyzEcvG11MvwvdAnOiWNivRXj5q6yoLCi7BRoALWXQkA84a8SApLobhcWNUwB5BTPu8yYNy+/aCUVwuankAowknbIX/74VD9IJAQbUd8iA9Isn8zPjXNvyxnfRU+2uUt+IBH4frFbdMWaRknP+OkfshbUDj0T1pygscrMtUDWMwiX0Y1/+rDG2qSeb1S9/cCOiuAYfP1XQ4IWwwastw1za9EyELx0CDLsIY3Xa0HW+AQsh4ufEtPB8uXakBtZJynzrnGAp6/2Vven9uc9Udzx1J904GldsBm+OYaJXdnNmeWBy2HYjve/SClV5joFvE/ts7Ff9W99i0NaO8ggLQ5mlIKOf/SA+EDJU6YjamCh6ivos7xdiZgWZsvKEXYSjUXGXLJBv3FG3ozrFACg7nj36zUM6mBxk1ssgSrCzNISASPerOA7tJCrSyip4bbGfAXlcNIzFlgJ+nG4C8y8w6JyO0bUEQyVIMzTEaCB6VWyFjF3xJrXVg1XFB1KCf6xtKP3HM=
  tag_name: $TAG_NAME
  name: buttplug-android $TAG_NAME
  file:
  - buttplug.apps.BluetoothDeviceEmulator/build/outputs/apk/debug/buttplug.apps.BluetoothDeviceEmulator-$TAG_NAME-debug.apk
#  - buttplug.apps.ExampleClientGUI/build/outputs/apk/debug/buttplug.apps.ExampleClientGUI-$TAG_NAME-debug.apk
  - buttplug.apps.WebsocketServerGUI/build/outputs/apk/debug/buttplug.apps.WebsocketServerGUI-$TAG_NAME-debug.apk
#  - buttplug.client/build/outputs/aar/buttplug.client-$TAG_NAME-debug.aar
  - buttplug.components.controls/build/outputs/aar/buttplug.components.controls-$TAG_NAME-debug.aar
  - buttplug.components.WebsocketServer/build/outputs/aar/buttplug.components.WebsocketServer-$TAG_NAME-debug.aar
  - buttplug.core/build/outputs/aar/buttplug.core-$TAG_NAME-debug.aar
  - buttplug.server/build/outputs/aar/buttplug.server-$TAG_NAME-debug.aar
  - buttplug.core/build/outputs/aar/buttplug.core-$TAG_NAME-debug.aar
  - buttplug.server.managers.AndroidBluetoothManager/build/outputs/aar/buttplug.server.managers.AndroidBluetoothManager-$TAG_NAME-debug.aar
  prerelease: true
  skip_cleanup: true
  on:
    repo: mftrips/buttplug-android
    branch: master
